on:
  workflow_dispatch:
  schedule:
    - cron: '45 15 */6 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/fc1um2-li3re4ro@cron
        with:
          token: ${{ secrets.token }}
